services:
  pokemon_test_api:
    build: bankaya-test
    ports:
      - "8080:8080"
    environment:
      DB_HOST:
      DB_PASSWORD:
      DB_USER_NAME:
    restart: always
    depends_on:
      bankaya_test_db:
        condition: service_healthy
      
  bankaya_test_db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_PASSWORD:
      MYSQ_USER:
      MYSQL_DATABASE: pokemon_test
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
